name: redstone_mapper_pg
version: 0.2.0-beta.2
author: Luiz Mineo <luiz.mineo@gmail.com>
description: PostgreSQL extension for redstone_mapper
homepage: http://redstonedart.org
environment:
  sdk: '>=1.9.0-dev.9.1 <2.0.0'
dependencies:
  redstone: "^0.6.7"
  redstone_mapper:
    git: https://github.com/RobertMcDermot/redstone_mapper.git
  postgresql: '^0.3.4'
dev_dependencies:
  test: "^0.12.0"
  mock: '^0.12.0'
